micronaut:
  application:
    name: micronaut-template
    default-charset: UTF-8
  server:
    port: 8080

  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /api/**
      swagger-ui:
        paths: classpath:swagger-ui
        mapping: /api/ui

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  prometheus:
    enabled: true
    sensitive: false

jackson:
  date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX